from __future__ import annotations


DEFAULT_DIAGNOSTICS = [
    "Full physical examination and vitals",
    "CBC/biochemistry when systemic disease is suspected",
    "Fecal/urine testing when gastrointestinal or urinary signs are present",
    "Imaging or ultrasound when pain, obstruction, trauma, or pregnancy complications are possible",
]

DEFAULT_TREATMENT_PRINCIPLES = [
    "Stabilize hydration, temperature, pain, and oxygenation as needed",
    "Use species-appropriate medicines only after veterinary assessment",
    "Confirm diagnosis before antimicrobials, steroids, or invasive treatment",
    "Give owners clear monitoring and return precautions",
]


CONDITION_RULES = [
    {
        "condition": "Canine parvoviral enteritis",
        "species": {"dog"},
        "urgency": "Emergency",
        "symptoms": {
            "vomiting": 25,
            "diarrhea": 25,
            "bloody": 20,
            "not vaccinated": 15,
            "lethargy": 10,
            "puppy": 10,
            "dehydration": 10,
        },
        "red_flags": ["Severe dehydration", "Bloody diarrhea", "Shock risk"],
        "diagnostics": ["Parvo antigen test", "CBC for leukopenia", "Hydration and perfusion assessment"],
        "treatment_principles": [
            "Isolation and infection control",
            "Aggressive fluid therapy if dehydrated",
            "Antiemetic, nutrition, and supportive care under vet supervision",
        ],
    },
    {
        "condition": "Gastroenteritis or dietary indiscretion",
        "species": {"dog", "cat"},
        "urgency": "Urgent",
        "symptoms": {
            "vomiting": 25,
            "diarrhea": 25,
            "new food": 15,
            "garbage": 15,
            "lethargy": 10,
            "abdominal pain": 15,
        },
        "red_flags": ["Repeated vomiting", "Dehydration", "Abdominal pain"],
        "diagnostics": ["Hydration assessment", "Fecal exam", "Abdominal imaging if pain or foreign body risk"],
        "treatment_principles": [
            "Fluid and electrolyte support when indicated",
            "Dietary management after vomiting is controlled",
            "Rule out obstruction, pancreatitis, toxins, and infectious disease",
        ],
    },
    {
        "condition": "Feline lower urinary tract disease / obstruction risk",
        "species": {"cat"},
        "urgency": "Emergency",
        "symptoms": {
            "straining": 25,
            "unable to urinate": 35,
            "not urinating": 35,
            "blood in urine": 15,
            "crying": 10,
            "male": 10,
            "lethargy": 10,
        },
        "red_flags": ["Male cat urinary obstruction can become rapidly fatal"],
        "diagnostics": ["Bladder palpation", "Urinalysis", "Renal values and electrolytes", "Imaging if stones suspected"],
        "treatment_principles": [
            "Immediate decompression if obstructed",
            "Pain control and fluid support under vet care",
            "Address stones, infection, stress, diet, or inflammation based on diagnostics",
        ],
    },
    {
        "condition": "Respiratory infection complex",
        "species": {"dog", "cat", "cattle", "goat", "sheep", "horse", "poultry"},
        "urgency": "Urgent",
        "symptoms": {
            "cough": 20,
            "nasal discharge": 20,
            "sneezing": 10,
            "fever": 15,
            "difficulty breathing": 35,
            "reduced appetite": 10,
            "eye discharge": 10,
        },
        "red_flags": ["Respiratory distress", "High fever", "Poor appetite"],
        "diagnostics": ["Auscultation", "Temperature", "Pulse oximetry if available", "Radiographs or lab testing when severe"],
        "treatment_principles": [
            "Separate contagious animals when appropriate",
            "Support oxygenation and hydration",
            "Select antimicrobials only when bacterial disease is likely or confirmed",
        ],
    },
    {
        "condition": "Tick-borne disease differential",
        "species": {"dog", "cattle", "goat", "sheep", "horse"},
        "urgency": "Urgent",
        "symptoms": {
            "ticks": 25,
            "tick": 25,
            "fever": 20,
            "lethargy": 15,
            "anemia": 20,
            "pale": 15,
            "jaundice": 20,
            "lameness": 10,
        },
        "red_flags": ["Anemia", "Jaundice", "Weakness"],
        "diagnostics": ["Tick check", "CBC/PCV", "Blood smear or vector-borne disease testing"],
        "treatment_principles": [
            "Stabilize anemia or weakness first",
            "Use targeted therapy after vet confirmation",
            "Tick control for patient and environment",
        ],
    },
    {
        "condition": "Mastitis",
        "species": {"cattle", "goat", "sheep"},
        "urgency": "Urgent",
        "symptoms": {
            "udder": 20,
            "swollen udder": 30,
            "milk clots": 25,
            "fever": 15,
            "pain": 10,
            "reduced milk": 15,
        },
        "red_flags": ["Toxic mastitis", "Fever with severe udder pain"],
        "diagnostics": ["Udder exam", "California mastitis test", "Milk culture where possible"],
        "treatment_principles": [
            "Milk-out and supportive care",
            "Choose therapy based on severity, species, withdrawal time, and vet rules",
            "Improve hygiene and milking management",
        ],
    },
    {
        "condition": "Bloat / ruminal tympany",
        "species": {"cattle", "goat", "sheep"},
        "urgency": "Emergency",
        "symptoms": {
            "bloated": 35,
            "bloat": 35,
            "left side": 15,
            "distended": 20,
            "difficulty breathing": 20,
            "not eating": 10,
            "fresh pasture": 10,
        },
        "red_flags": ["Rapid abdominal distension", "Breathing compromise"],
        "diagnostics": ["Visual abdominal assessment", "Rumen motility", "Differentiate frothy vs free-gas bloat"],
        "treatment_principles": [
            "Emergency decompression when severe",
            "Manage frothy or free-gas cause appropriately",
            "Review feed transition and pasture risk",
        ],
    },
    {
        "condition": "Lameness / trauma differential",
        "species": {"dog", "cat", "cattle", "goat", "sheep", "horse"},
        "urgency": "Urgent",
        "symptoms": {
            "lameness": 25,
            "limping": 25,
            "swelling": 15,
            "wound": 20,
            "trauma": 20,
            "pain": 15,
            "not bearing weight": 25,
        },
        "red_flags": ["Non-weight-bearing limb", "Open wound", "Fracture risk"],
        "diagnostics": ["Gait exam", "Pain localization", "Wound assessment", "Radiographs if fracture or joint injury possible"],
        "treatment_principles": [
            "Restrict movement until assessed",
            "Provide vet-directed analgesia",
            "Clean and protect wounds; avoid unsafe human pain medicines",
        ],
    },
    {
        "condition": "Poultry respiratory disease differential",
        "species": {"poultry"},
        "urgency": "Urgent",
        "symptoms": {
            "cough": 15,
            "sneezing": 20,
            "nasal discharge": 20,
            "swollen face": 20,
            "reduced eggs": 15,
            "mortality": 25,
            "difficulty breathing": 30,
        },
        "red_flags": ["High mortality", "Respiratory distress", "Possible reportable disease"],
        "diagnostics": ["Flock history", "Mortality rate", "Necropsy/lab testing when indicated"],
        "treatment_principles": [
            "Isolate affected birds and improve ventilation",
            "Check local reporting rules for severe or unusual outbreaks",
            "Use medication only under vet direction with food-animal compliance",
        ],
    },
]
